language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
script:
- "./src/SaltVault.WebApp/build.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_03320890e2fa_key -iv $encrypted_03320890e2fa_iv
  -in Config.tar.enc -out Config.tar -d
- openssl aes-256-cbc -K $encrypted_6fa44c9403f6_key -iv $encrypted_6fa44c9403f6_iv
  -in bot_token.config.enc -out bot_token.config -d
- openssl aes-256-cbc -K $encrypted_791e4b4009c2_key -iv $encrypted_791e4b4009c2_iv
  -in ClientIds.config.enc -out ClientIds.config -d
- openssl aes-256-cbc -K $encrypted_791e4b4009c2_key -iv $encrypted_791e4b4009c2_iv
  -in LIVEConnectionString.config.enc -out LIVEConnectionString.config -d
