language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
script:
- "./src/SaltVault.WebApp/build.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_be46889660c0_key -iv $encrypted_be46889660c0_iv
  -in ./src/SaltVault.WebApp/Data/Config.tar.enc -out ./src/SaltVault.WebApp/Data/Config.tar -d
