language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
script:
- "./src/SaltVault.WebApp/build.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_03320890e2fa_key -iv $encrypted_03320890e2fa_iv
  -in Config.tar.enc -out Config.tar -d
  - tar xvf Config.tar